### ISSUE TITLE
 Oops, something went wrong

### ISSUE THREAD

**Issue by adminpb** [yannrouillard/aws-sso-profiles-switcher#8] opened 2023-08-27 17:52 UTC
I always get this error after switching, but after refreshing the page, everything loads fine.
![изображение](https://github.com/yannrouillard/aws-sso-profiles-switcher/assets/4687120/5f4a408c-a0db-4fff-b7e2-879da7689e7f)

**Comment by yannrouillard** [comment] 2023-09-16 10:53
Hi @adminpb 

A 429 HTTP code usually indicates Too Many Requests issue: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

I am not yet sure why it could happen in your case (unless there is some specific conditions triggering some loop calling AWS multiple times).

Let me come back to you with some instructions about how to provide me more logs about what is happening.

**Comment by adminpb** [comment] 2023-09-16 10:59
> Hi @adminpb
> 
> A 429 HTTP code usually indicates Too Many Requests issue: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
> 
> I am not yet sure why it could happen in your case (unless there is some specific conditions triggering some loop calling AWS multiple times).
> 
> Let me come back to you with some instructions about how to provide me more logs about what is happening.

Hello. This error was observed only in the first days of using the add-on. Currently, this error is not present, and everything works fine. Thx!

**Comment by yannrouillard** [comment] 2023-09-16 11:25
Ok, I still wonder what could have been the cause, but since it's not reproducible, I will close the issue soon.

Anyway, don't hesitate to open an issue again if some new issue pops up in the future, or if you have other feedback about the extension!

**Closed** 2023-09-16 16:36 UTC
